project:
  type: website
  output-dir: docs

website:
  title: "As-yet-undecided"
  description: "Matthew Scott's personal website. Undecided on the content."
  reader-mode: true
  navbar:
    title: "As-yet-undecided"
    background: "#096367"
    pinned: true
    #left:
    #  - text: "Some text here"
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - icon: github
        href: https://github.com/mc-scott/ds-blog
  page-footer:
    left:
    - href: https://www.quarto.org
      text: Built with Quarto
    right: 
      - href: license.qmd
        text: License

format:
  html:
    #code-overflow: wrap # this doesn't seem to render correctly
    highlight-style: atom-one
    code-block-bg: true
    code-block-border-left: "#096367"
    theme: 
      light: flatly
      #dark: darkly # add a second dark theme & toggle
